
services:
  PostgreSql:
   image: ${POSTGRES_IMAGE}
   container_name: Postgresql
   environment:
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_DB=${POSTGRES_DB}
   restart: always
   env_file: 
    - .env
   ports:
    - ${POSTGRES_PORTS}:5432
   volumes:
   - CuidandoPawsDb:/var/lib/postgresql/data
  
  CuidandoPaws:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CuidandoPawsBackend
    image: wdelacruzdev/cuidando-paws-backend:0.0.1
    restart: always
    depends_on:
      - PostgreSql
    ports:
      - ${CUIDANDO_PAWS_PORTS}:5050
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}

  PgAdmin:
   depends_on: 
   - PostgreSql
   image: dpage/pgadmin4:6.17
   container_name: PgAdmin
   restart: always
   env_file:
    - .env
   ports:
    - "${PGADMIN_PORTS}:80" 
   environment:
   - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
   - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
   volumes:
   - PgAdmin:/var/lib/pgadmin
   
 
volumes:
  CuidandoPawsBackend:
  CuidandoPawsDb:
  PgAdmin:  