// <auto-generated />
using System;
using CuidandoPawsApi.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CuidandoPawsApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CuidandoPawsContext))]
    [Migration("20241028003543_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CuidandoPawsApi.Domain.Models.Adoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdoptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPets")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id")
                        .HasName("PK_Adoption")
                        .HasAnnotation("Npgsql:IdentityStart", 10000);

                    b.HasIndex("IdPets")
                        .IsUnique();

                    b.ToTable("Adoptions");
                });

            modelBuilder.Entity("CuidandoPawsApi.Domain.Models.Appoinment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_Appoinment")
                        .HasAnnotation("Npgsql:IdentityStart", 10000);

                    b.ToTable("Appoinments");
                });

            modelBuilder.Entity("CuidandoPawsApi.Domain.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPet")
                        .HasColumnType("integer");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_MedicalRecord")
                        .HasAnnotation("Npgsql:IdentityStart", 10000);

                    b.HasIndex("IdPet")
                        .IsUnique();

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("CuidandoPawsApi.Domain.Models.Pets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdoptionStatus")
                        .HasColumnType("boolean");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Bred")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfEntry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamePaws")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_Pet")
                        .HasAnnotation("Npgsql:IdentityStart", 10000);

                    b.HasIndex("SpeciesId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("CuidandoPawsApi.Domain.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Species")
                        .HasAnnotation("Npgsql:IdentityStart", 10000);

                    b.ToTable("Species");
                });

            modelBuilder.Entity("CuidandoPawsApi.Domain.Models.Adoption", b =>
                {
                    b.HasOne("CuidandoPawsApi.Domain.Models.Pets", "Pets")
                        .WithOne("Adoption")
                        .HasForeignKey("CuidandoPawsApi.Domain.Models.Adoption", "IdPets")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Pets");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("CuidandoPawsApi.Domain.Models.MedicalRecord", b =>
                {
                    b.HasOne("CuidandoPawsApi.Domain.Models.Pets", "Pet")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("CuidandoPawsApi.Domain.Models.MedicalRecord", "IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MedicalRecord");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("CuidandoPawsApi.Domain.Models.Pets", b =>
                {
                    b.HasOne("CuidandoPawsApi.Domain.Models.Species", "Species")
                        .WithMany("Pets")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Species");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("CuidandoPawsApi.Domain.Models.Pets", b =>
                {
                    b.Navigation("Adoption");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("CuidandoPawsApi.Domain.Models.Species", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
